plugins {
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'com.example'
version = '0.1.0'

sourceCompatibility = '17'

application {
    mainClass = 'com.example.swingjack.BlackjackGUI'
}

repositories {
    mavenCentral()
}

dependencies {

}

shadowJar {
    archiveBaseName.set('swingjack')
    archiveClassifier.set('all')
}
